### ISSUE TITLE
createkeys always creates keys in ${DEFAULT}/keys

### ISSUE THREAD

**Issue by stevie-** [voxpupuli/puppet-hiera#118] opened 2016-02-24 11:16 UTC
If we change parameter keysdir, the create exec will still create keys in default dir /var/lib/puppet/keys.

Exec command for create keys needs to specify where to store key files.

**Comment by hunner** [comment] 2016-02-29 22:48
This should be fixed in the master branch: https://github.com/hunner/puppet-hiera/blob/master/manifests/eyaml.pp#L24

**Comment by stevie-** [comment] 2016-03-02 08:09
We used tag 2.0.1 which seems to be same code.

My point is, that by default eyaml createkeys without parameters will create keys always in subdir keys.

If we set up in puppet keysdir to "/path/to/eyaml_keys" it would create "/path/to/keys"

**Comment by vStone** [comment] 2016-11-18 10:04
I'm not able to reproduce this (see tests)

**Closed** 2023-06-20 08:38 UTC
